env: development
src: _project
dist: project
cache: true
ibooks_specified_fonts: false
theme: b-ber-theme-serif
themes_directory: ./themes
base_url: 'http://localhost:4000/project-web'
base_path: /
remote_url: 'http://localhost:4000/'
reader_url: 'http://localhost:4000/project-reader'
downloads: []
ui_options:
  navigation:
    header_icons:
      info: false
      home: false
      downloads: true
      toc: true
    footer_icons:
      chapter: true
      page: false
private: false
ignore: []
autoprefixer_options:
  overrideBrowserslist:
    - defaults
    - '> 1%'
    - not dead
    - not IE 11
  flexbox: no-2009
layout: columns
group_footnotes: true
